services:
  postgres:
    image: postgres:15-alpine
    container_name: liquibase-postgres
    environment:
      POSTGRES_DB: liquibasedb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"